### ISSUE TITLE
`[sig-apps] CronJob should not emit unexpected warnings` fails

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon-rs#737]
### Which jobs are failing?

CRI-O conmonrs e2e feature tests.

### Which tests are failing?

Mentioned in the title, ran via: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/cri-o_cri-o/6220/pull-ci-cri-o-cri-o-main-ci-e2e-conmonrs/1572188830188965888

### Since when has it been failing?

Since ever, reproducible with 8e4cec9644f742be8334ea8ecfc9f895b1d6691e

**Comment by saschagrunert** [comment]
The reason for this test to fail is that pods like this do not exit and keep running:

```
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  restartPolicy: Never
  containers:
  - image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    name: c
```

In conmon they immediately complete, in conmon-rs they still keep running forever.
